services:
  mongodb:
    image: mongo:7
    container_name: ragulate_mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ragulate_backend_v2
    restart: unless-stopped
    depends_on:
      - mongodb
    ports:
      - "8000:8000"
    env_file:
      - ".env"

volumes:
  mongo_data:
